# Generated by Django 6.0.7 on 2026-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Aluno ativo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=30, verbose_name='Turma'),
        ),
    ]
