# Generated by Django 6.0.7 on 2026-07-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda', '0003_cardapio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('horario_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Horário de entrada')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('ATENDIDO', 'Atendido'), ('DESISTIU', 'Desistiu'), ('BLOQUEADO', 'Bloqueado')], default='AGUARDANDO', max_length=20, verbose_name='Status')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merenda.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Fila',
                'ordering': ['horario_entrada'],
            },
        ),
    ]
