# Generated by Django 6.0.7 on 2026-07-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda', '0004_fila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_atendimento', models.DateTimeField(auto_now_add=True, verbose_name='Horário do atendimento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merenda.aluno', verbose_name='Aluno')),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merenda.cardapio', verbose_name='Cardápio')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-horario_atendimento'],
            },
        ),
    ]
