# Generated by Django 6.0.7 on 2026-07-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merenda', '0005_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merenda.cardapio', verbose_name='Cardápio'),
        ),
    ]
